- crawlera.rst
@pablohoffman @qrilka @serhiy-yasko please let me know what you think of the intro and if anything needs to be changed.
> Added introduction to Crawlera docs

- _static/crawlera-python-requests-2.py
- _static/crawlera-python-requests.py
- crawlera.rst
Perhaps I should lose the first Requests example?
> Adding another Requests example for Crawlera

- crawlera.rst
Since the selected headers are available for Crawlera Shared Monthly plans too.
> Rewording the subnote of Crawlera x-headers

- frontier.rst
Just adding note about listing frontiers and slots.
> Documenting the frontier listing API

- dash.rst
> update job outcomes

- crawlera.rst
Resolves RM #31205
@michalmo please review, thanks.
> Add documentation for Crawlera API keys and account upgrade

- _static/sc-crunchbase.py
> Updated import statements for Crunchbase spider example

- crawlera.rst
Updated library name for Crawlera middleware
> Updated reference to Crawlera middleware

- crawlera.rst
Corrected case of questions in Crawlera FAQ.
> Corrected case of Crawlera FAQ questions

- crawlera.rst
Added question to FAQ on how request speed differs when using Crawlera as opposed to routing requests through proxies directly.
@qrilka can you please review? Thanks
> Added question to FAQ on delays discrepancy

- crawlera.rst
@qrilka can you please review? Thanks.
> Added X-Crawlera-Timeout header documentation

- shub.rst
Please review and merge.
Thanks.
> Command Line Client (shub) documentation

- scrapy-cloud.rst
@dangra can you please review & merge if it's accurate
@immerrr @shaneaevans "private API" is the best way I cloud find to describe jobq API, I'm not proud about it. We need #oneapi!
/cc @kmike @redapple
> add documentation about running custom scripts on scrapy cloud

- crawlera.rst
added here: https://github.com/scrapinghub/crawlera/pull/512
> crawlera: adding session api creation #38946

- scrapy-cloud.rst
Updated docs to reflect plan changes
> Updated Scrapy Cloud plans information

- scrapy-cloud.rst
To address https://github.com/scrapinghub/doc.scrapinghub.com/pull/90/files#r39401516
(next time I'll request review)
> Forgot to remove '2 plan' line

- crawlera.rst
part of the https://intranet.scrapinghub.com/issues/41929 ticket
> update crawlera headers plan

- crawlera.rst
Removed at @federicozaiter 's request.
> Removed 'How do I add proxies in Crawlera?' from Crawlera FAQ

- activity.rst
- api.rst
- collections.rst
- comments.rst
- frontier.rst
- jobdata.rst
- jobs.rst
- reports.rst
Add redirects from old pages to equivalent new pages.
> Added redirects from old pages

- addons.rst
Also made DotScrapy requirement more obvious.
> Added note on DF limiting to item-only requests

- crawlera.rst
nothing to pass, only a POST request.
> only post request when creating new crawlera session

- api/jobs.rst
> Update docs for Dash

- shub.rst
Updates the documentation to conform to the changes made in shub: https://github.com/scrapinghub/shub/pull/87
> update log and requests commands example for shub

- _static/crawlera-curb.rb
- _static/crawlera-httpc.java
- _static/crawlera-mechanize.rb
- _static/crawlera-php-binding.php
- _static/crawlera-php-symfony.php
- _static/crawlera-python-requests-httpproxyauth.py
- _static/crawlera-typhoeus.rb
- crawlera.rst
https://intranet.scrapinghub.com/issues/44122
> Adding a note about CONNECT in the examples section

- api/collections.rst
Also added missing APIKEY placeholders to examples
> Updated parameter names (:id to :project_id) in collections API

- scrapy-cloud.rst
To be merged after DASH-227 goes live.
> Update Scrapy Cloud docs for new Deploy page

- crawlera.rst
> new value for x-crawlera-timeout header

- crawlera.rst
- index.rst
- scrapy-cloud.rst
Update some links to their https correspondent link
> Update some links to https

- _themes/shub-doc/layout.html
The goal here is to create heatmaps from users' activities in our docs using [HotJar](https://www.hotjar.com/), so that we can check whether they are finding the info they are looking for.
> Add HotJar tracking code to doc.scrapinghub.com

- api/jobq.rst
> Add description for JobQ /count endpoint

- api/jobq.rst
Addressing [the comment](https://github.com/scrapinghub/doc.scrapinghub.com/pull/155#issuecomment-266700099).
Review, please.
> Improve JobQ doc for has_tag/lacks_tag

- api/requests.rst
'time' and 'method' fields are required.
> Update Request API documentation

- api/collections.rst
- api/jobq.rst
- api/logs.rst
Minor fixes to have more precise definition of UNIX timestamp-based fields.
> Fix UNIX timestamp-based fields definition

- crawlera.rst
Formatting last links updated today, to avoid long address.
Please review if the code is correct, thanks!
> Formatting last links updated

- crawlera.rst
First test using local git:
Dear Valdir, please check for updates and make any necessary corrections to this PR.
Thanks!
> Links updates (Using different languages)

- api/collections.rst
- add quickstart
- add details on limitations
- add missing endpoints (listing, etc)
- contains update for the new endpoints (immediate delete & renames)
> Update api collections

- scrapy-cloud.rst
Let me know if you have a better wording in mind.
> Use offset param when paginating with app.sh.com

- autoextract.rst
- index.rst
Note: this should not go live yet, but I'm not sure about the process for docs update.
Things which I'm not sure about:
- "Before you Begin" might need to be updated, as this was written specifically for the beta. @waynespeight do you know what would be the process?
- Is it fine to include a link in index.rst?
Github-rendered page: https://github.com/scrapinghub/doc.scrapinghub.com/blob/autoextract-api/autoextract.rst
> Add docs for AutoExtract API

- api/jobmeta.rst
- api/jobq.rst
- scrapy-cloud.rst
> Document storage /jobs endpoint
