- api.rst
Hi!
Adding a note about limited random access options for collections API because the docs currently imply it supports random access just like the other APIs (it ignores `index` and does not support `start=random`).
> adding note about limited random access for collections API

- crawlera.rst
Please note that the sessions API, shorter lifetime and limitation are not deployed yet.
> Document crawlera sessions API

- dash.rst
It lead to CloseSpider *exception* previously.
> dash.rst: fix Scrapy CloseSpider extension link

- Makefile
- shub.rst
Hey folks,
The motivation for this PR is to enable an user to know the features available in shub: http://doc.scrapinghub.com/shub.html
Today, an user has to install the tool to find out what it can do.
The goal was also to have minimal friction to update it, so the usage information is obtained through `make syncshub`, which will just use the output of `shub --help` -- this way anyone with the latest version of shub installed locally can update it without much hassle.
Does this look good?
Note: Let's wait for the shub's release before merging this (should happen next week).
> Show shub usage in the page, add syncshub Makefile target to update it

- _static/crawlera-httpc.java
- _static/crawlera-proxy.cs
- crawlera.rst
Added note on pre-emptive authentication to example section of Crawlera doc. Also updated .NET and Java code examples.
@qrilka can you review? Thanks.
> Add note on pre-emptive authentication to Crawlera documentation

- crawlera.rst
Per @serhiy-yasko 's request I've corrected some errors in the Crawlera documentation:
1. Crawlera list sessions and delete sessions documentation described using curl's `-U` switch for authentication. This is incorrect as it instructs curl to use the authentication details with the proxy. This has been corrected to use the `-u` switch which instead provides authentication to the server.
2. Session lifetime was described as 1 hour. This has been corrected to 30 minutes. (https://github.com/scrapinghub/crawlera/blob/develop/src/pm_sessions.erl#L23)
3. Maximum number of sessions was described as 10. This has been corrected to 100. (https://github.com/scrapinghub/crawlera/blob/develop/src/pm_sessions.erl#L25)
@qrilka can you please confirm before I merge? Thanks.
> Crawlera documentation corrections

- _static/crawlera-httpc.java
- crawlera.rst
Basic scheme should be applied to proxy not target website and https://issues.apache.org/jira/browse/HTTPCLIENT-1599 requires extra step to set it up for proxies.
> Fixed Java Crawlera example

- crawlera.rst
It was enabled for ordinary Crawlera users in Crawlera 1.4.2, see https://github.com/scrapinghub/crawlera/pull/477
> Remove paygo warning for X-Crawlera-Session

- _static/crawlera-curb.rb
- _static/crawlera-httpc.java
- _static/crawlera-php-binding.php
- _static/crawlera-proxy.cs
- _static/crawlera-python-requests-httpproxyauth.py
- _static/crawlera-request.js
- _static/crawlera-typhoeus.rb
- crawlera.rst
- Refactoring paygo to proxy.crawlera.com in:
Examples from every programming language listed
- Removing X-Crawlera-NO-UA (deprecated)
- Changing "Not available on Pay-as-You-Go plan." to "Only available on C50, C100, C200 and Enterprise plans."
> Refactoring paygo to proxy.crawlera.com in docs and examples

- crawlera.rst
Added a brief section on using cookies with Crawlera, explaining that Crawlera cookie tracking should be disabled if managing cookies in your spider, and mentioning the retention of 15 minutes.
@pawelmhm / @qrilka can you please review? Thanks.
> Added info on Crawlera cookie tracking

- dash.rst
Dash UI says this in the pop-over:
> The job was cancelled because either it has failed to shutdown gracefully after cancellation (taking more than 5 minutes) or it hasn’t been producing anything (not even log entries) for an hour
but I think the latter reason gets "cancelled" as outcome.
> [Scrapy Cloud/Dash] Add desccription of `cancel_timeout` outcome

- _static/crawlera-httpc.java
`X-Crawlera-Use-HTTPS` is supposed to be used with `http` scheme.
> Update docs for CRAWLERA-2040

- api/client_library.rst
- api/frontier.rst
- api/items.rst
- api/jobq.rst
- api/overview.rst
- api/requests.rst
This PR adds `python-hubstorage` examples for:
* Frontier
* Items
* JobQ
* Requests
> Add python-hubstorage examples

- api/client_library.rst
It was not working in the jobs page.
> fix broken link to python-hubstorage

- api/eggs.rst
> Fix wrong method description for listing project eggs via API

- scrapy-cloud.rst
I will post another PR after the new `Code & Deploy` page goes live in Dash. (Replacing "get api key from your account page and project id from URL" with "get both from your code & deploy page")
> Update Scrapy Cloud page to reflect new shub features

- scrapy-cloud.rst
`entry_points` line is essential, it's the way project provides default settings path to Scrapy Cloud (because scrapy.cfg is not included in the egg).
Also made 1st `setup.py` example consistent with following `setup.py` example that shows how to run custom python scripts.
> Update setup.py example

- _themes/shub-doc/layout.html
Segment tracking hasn't been working since April for our websites. This PR fix the Segment tracking code to make it work on doc.scrapinghub.com again.
> Fix segment analytics tracking code

- _static/crawlera-splash.lua
In Lua `type(nil) == 'nil'`, not `nil`. It might cause issues (e.g. erasing existing Crawlera session and requesting a new one) in some specific cases.
> Fixed: Incorrectly handling Crawlera sessions with Lua script on Splash

- Makefile
- conf.py
- shub.rst
Merge only after `shub 2.5` is released & docs are built.
> Link to shub documentation instead of parsing its README

- api/frontier.rst
The correct endpoint to list the frontiers is **/hcf/:project_id/list**.
> Fix frontier API endpoint

- scrapy-cloud.rst
- Replace deprecated scheduler.json with run.json.
- Remove tabs from documentation source.
> Add run.json example with job_settings

- api/jobs.rst
Fix the path ('jobs/run.json' does not exist) and the parameters description. Remove a reference to the deprecated 'schedule' endpoint.
> Fix run endpoint documentation

- api/activity.rst
- api/client_library.rst
- api/collections.rst
- api/comments.rst
- api/frontier.rst
- api/items.rst
- api/jobq.rst
- api/jobs.rst
- api/logs.rst
- api/requests.rst
- scrapy-cloud.rst
- Remove references to deprecated python-hubstorage.
- Update python-scrapinghub description.
- Remove python examples from this site because python-scrapinghub
now provides a very comprehensive documentation on Read The Docs.
Fixes #156
> Update docs with a link to the updated Python client

- crawlera.rst
We are moving the KB to Freshdesk and updating old links from Help in Intercom.
> Update legacy links to help center

- api/jobs.rst
As far as I know it's not currently possible to specify a custom job ID when scheduling a job on Scrapy Cloud. I'm not sure if it was possible in the past, but I think the current IDs are just sequential numbers.
I tried passing a `job` parameter using curl and the parameter is then passed to the spider as a normal spider parameter on Scrapy Cloud, it doesn't seem to be recognised as a special parameter.
> Remove job parameter in the run.json endpoint

- api/items.rst
- api/logs.rst
- api/requests.rst
- scrapy-cloud.rst
There was a question about correct pagination usage, and looks like current documentation could be improved: I was able to find pagination logic details [here](https://doc.scrapinghub.com/scrapy-cloud.html#pagination) and a corresponding link in the left menu, but users can still skip it accidentally when checking info about parameters of specific items/requests/logs endpoints. 
The PR tries to improve it for the endpoints and adds some additional examples, review please.
> Improve documentation about pagination usage

- crawlera.rst
This poses more questions than what it actually answers.
Correcting also inverted value, the default delay between the same IP was 12 not 1.
And making this section more relevant to Session users.
> editing sessions limit section

- crawlera.rst
Now it says "https://scrapinghub.com/pricing/#crawlera" where actually should say https://scrapinghub.com/crawlera
> fix crawlera pricing link.

- crawlera.rst
This PR introduces new `X-Crawlera-Profile-Pass` header we are going to introduce in the next Crawlera release.
Long story short: profile header values override user values by default. If the user wants to provide her own values, she needs to use new header, `X-Crawlera-Profile-Pass`
> [MRG+1] Describe X-Crawlera-Profile-Pass

- crawlera-stats.rst
make html shows a warning without it:
> WARNING: /Users/kmike/svn/doc.scrapinghub.com/crawlera-stats.rst:20: (WARNING/2) Title underline too short.
> fixed "Title underline too short" warning in crawlera-stats.rst
